spring.application.name=Expense-Tracker-API
#MySQL Connection Configuration -my added
#spring.datasource.url=jdbc:mysql://localhost:3306/ExpenseTrackerApiDb
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
##Hibernate Configuration - my added
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
## This tells Spring Boot to only print the root exception message, skipping the chain
##logging.exception-conversion-word=%wEx{short}
#spring.jpa.open-in-view=false
