spring.application.name=Expense-Tracker-API

# MySQL Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ExpenseTrackerApiDb
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
